### ISSUE TITLE
RA_Proyecto Final

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/actividad-11-proyecto-final-de-realidad-aumentada-team-vo#1]
[RA_ProyectoFinal.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-proyecto-final-de-realidad-aumentada-team-vo/files/15494396/RA_ProyectoFinal.pdf)

**Comment by josealfredo79** [comment]
Bien hecho revisado...Calificacion 20
